/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIImageView, UILabel, UIPushButton;

@interface UICalloutView : UIControl
{
    UIImageView *_leftCap;
    UIImageView *_rightCap;
    UIImageView *_topAnchor;
    UIImageView *_bottomAnchor;
    UIImageView *_leftBackground;
    UIImageView *_rightBackground;
    UIPushButton *_button;
    UILabel *_title;
    UILabel *_subtitle;
    UILabel *_temporary;
    struct {
        struct CGPoint origin;
        struct CGPoint offset;
        int position;
    } _anchor;
    struct CGRect _frame;
    id _delegate;
    struct {
        unsigned int animated:1;
        unsigned int didMoveSelectorCalled:1;
        unsigned int reserved:30;
    } _flags;
}

+ (id)_buttonImage;
+ (id)_buttonImagePressed;
+ (id)_backgroundImage;
+ (id)_leftCapImage;
+ (id)_rightCapImage;
+ (id)_topAnchorImage;
+ (id)_bottomAnchorImage;
+ (float)defaultHeight;
+ (id)sharedCalloutView;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setSubtitle:(id)fp8;
- (id)subtitle;
- (void)setTemporaryTitle:(id)fp8;
- (id)temporaryTitle;
- (void)setOffset:(struct CGPoint)fp8;
- (struct CGPoint)offset;
- (struct CGPoint)anchorPoint;
- (void)getActualAnchorPoint:(struct CGPoint *)fp8 frame:(struct CGRect *)fp12 position:(int *)fp16 forDesiredAnchorPoint:(struct CGPoint)fp20 boundaryRect:(struct CGRect)fp28;
- (void)_setOriginForScale:(float)fp8;
- (void)setAnchorPoint:(struct CGPoint)fp8 boundaryRect:(struct CGRect)fp16 animate:(BOOL)fp32;
- (void)animationDidStop:(id)fp8 finished:(id)fp12;
- (void)fadeOutWithDuration:(float)fp8;
- (void)completeBounceAnimation;
- (void)addTarget:(id)fp8 action:(SEL)fp12;
- (void)removeTarget:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;

@end

